### ISSUE TITLE
Snapshot fails to be saved after creating new projection and saga

### ISSUE THREAD

**Issue by hengkysucanda** [pawelkaczor/akka-ddd#30]
I received looping error messages saying:

SaveSnapshotFailure(SnapshotMetadata(Receptor-users-2037377487,5470,0),akka.pattern.CircuitBreakerOpenException: Circuit Breaker is open; calls are failing fast) going on

Until the backend app OOM and crashed.

**Comment by hengkysucanda** [comment]
Additional logs i picked up from when everytime the app is starting

```
at akka.persistence.eventstore.Helpers$RichConnection$.akka$persistence$eventstore$Helpers$RichConnection$$loop$1(Helpers.scala:52)
at akka.persistence.eventstore.Helpers$RichConnection$$anonfun$akka$persistence$eventstore$Helpers$RichConnection$$foldLeft$1$1.apply(Helpers.scala:57)
at akka.persistence.eventstore.Helpers$RichConnection$$anonfun$akka$persistence$eventstore$Helpers$RichConnection$$foldLeft$1$1.apply(Helpers.scala:56)
at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Unimplemented deserialization of message with manifest [akka.cluster.sharding.ShardCoordinator$Internal$State] in [akka.cluster.sharding.protobuf.ClusterShardingMessageSerializer]
at akka.cluster.sharding.protobuf.ClusterShardingMessageSerializer.fromBinary(ClusterShardingMessageSerializer.scala:162)
at akka.serialization.SerializerWithStringManifest.fromBinary(Serializer.scala:131)
at akka.serialization.Serialization$$anonfun$deserialize$3.apply(Serialization.scala:193)
at scala.util.Try$.apply(Try.scala:192)
at akka.serialization.Serialization.deserialize(Serialization.scala:193)
at pl.newicom.eventstore.json.SnapshotJsonSerializer$$anonfun$deserialize$1.applyOrElse(JsonSerializerExtension.scala:118)
at pl.newicom.eventstore.json.SnapshotJsonSerializer$$anonfun$deserialize$1.applyOrElse(JsonSerializerExtension.scala:112)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at pl.newicom.eventstore.json.ScheduledEventSerializer$$anonfun$deserialize$2.applyOrElse(JsonSerializerExtension.scala:84)
at pl.newicom.eventstore.json.ScheduledEventSerializer$$anonfun$deserialize$2.applyOrElse(JsonSerializerExtension.scala:84)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:393)
at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:393)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:393)
at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:393)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
... 31 more
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
at scala.collection.AbstractMap.applyOrElse(Map.scala:59)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.Extraction$.org$json4s$Extraction$$customOrElse(Extraction.scala:593)
at org.json4s.Extraction$ClassInstanceBuilder.result(Extraction.scala:580)
at org.json4s.Extraction$.extract(Extraction.scala:389)
at org.json4s.Extraction$ClassInstanceBuilder.org$json4s$Extraction$ClassInstanceBuilder$$mkWithTypeHint(Extraction.scala:575)
at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$result$8.apply(Extraction.scala:584)
at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$result$8.apply(Extraction.scala:580)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.Extraction$ClassInstanceBuilder.result(Extraction.scala:580)
at org.json4s.Extraction$.extract(Extraction.scala:389)
at org.json4s.Extraction$.extract(Extraction.scala:39)
at org.json4s.Extraction$.org$json4s$Extraction$$customOrElse(Extraction.scala:594)
org.json4s.package$MappingException: unknown error
at org.json4s.Extraction$.extract(Extraction.scala:43)
at org.json4s.ExtractableJsonAstNode.extract(ExtractableJsonAstNode.scala:21)
at org.json4s.native.Serialization$.read(Serialization.scala:71)
at org.json4s.Serialization$class.read(Serialization.scala:30)
at org.json4s.native.Serialization$.read(Serialization.scala:32)
at pl.newicom.eventstore.json.JsonSerializerExtensionImpl.fromBinary(JsonSerializerExtension.scala:44)
at pl.newicom.eventstore.EventstoreSerializationSupport$class.deserialize(EventstoreSerializationSupport.scala:98)
at pl.newicom.eventstore.EventstoreSerializationSupport$class.fromEvent(EventstoreSerializationSupport.scala:61)
at pl.newicom.eventstore.plugin.EventStoreSerializer.fromEvent(EventStoreSerializer.scala:10)
at pl.newicom.eventstore.plugin.EventStoreSerializer.fromEvent(EventStoreSerializer.scala:27)
at akka.persistence.eventstore.EventStoreSerialization.deserialize(EventStoreSerialization.scala:13)
at akka.persistence.eventstore.snapshot.EventStoreSnapshotStore$$anonfun$loadAsync$1$$anonfun$apply$1.applyOrElse(EventStoreSnapshotStore.scala:35)
at akka.persistence.eventstore.snapshot.EventStoreSnapshotStore$$anonfun$loadAsync$1$$anonfun$apply$1.applyOrElse(EventStoreSnapshotStore.scala:35)
at akka.persistence.eventstore.snapshot.EventStoreSnapshotStore$$anonfun$loadAsync$1.akka$persistence$eventstore$snapshot$EventStoreSnapshotStore$$anonfun$$fold$1(EventStoreSnapshotStore.scala:24)
at scala.PartialFunction$Lifted.apply(PartialFunction.scala:223)
at scala.PartialFunction$Lifted.apply(PartialFunction.scala:219)
at akka.persistence.eventstore.Helpers$RichConnection$.akka$persistence$eventstore$Helpers$RichConnection$$loop$1(Helpers.scala:52)
at akka.persistence.eventstore.Helpers$RichConnection$$anonfun$akka$persistence$eventstore$Helpers$RichConnection$$foldLeft$1$1.apply(Helpers.scala:57)
at akka.persistence.eventstore.Helpers$RichConnection$$anonfun$akka$persistence$eventstore$Helpers$RichConnection$$foldLeft$1$1.apply(Helpers.scala:56)
at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
at akka.serialization.Serialization$$anonfun$deserialize$3.apply(Serialization.scala:193)
at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Unimplemented deserialization of message with manifest [akka.cluster.sharding.ShardCoordinator$Internal$State] in [akka.cluster.sharding.protobuf.ClusterShardingMessageSerializer]
at akka.cluster.sharding.protobuf.ClusterShardingMessageSerializer.fromBinary(ClusterShardingMessageSerializer.scala:162)
at akka.serialization.SerializerWithStringManifest.fromBinary(Serializer.scala:131)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
at scala.util.Try$.apply(Try.scala:192)
at akka.serialization.Serialization.deserialize(Serialization.scala:193)
at pl.newicom.eventstore.json.SnapshotJsonSerializer$$anonfun$deserialize$1.applyOrElse(JsonSerializerExtension.scala:118)
at pl.newicom.eventstore.json.SnapshotJsonSerializer$$anonfun$deserialize$1.applyOrElse(JsonSerializerExtension.scala:112)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at pl.newicom.eventstore.json.ScheduledEventSerializer$$anonfun$deserialize$2.applyOrElse(JsonSerializerExtension.scala:84)
at pl.newicom.eventstore.json.ScheduledEventSerializer$$anonfun$deserialize$2.applyOrElse(JsonSerializerExtension.scala:84)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:393)
at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:393)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:393)
at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:393)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
... 31 more
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.Extraction$.org$json4s$Extraction$$customOrElse(Extraction.scala:593)
at org.json4s.Extraction$ClassInstanceBuilder.result(Extraction.scala:580)
at org.json4s.Extraction$.extract(Extraction.scala:389)
at org.json4s.Extraction$ClassInstanceBuilder.org$json4s$Extraction$ClassInstanceBuilder$$mkWithTypeHint(Extraction.scala:575)
at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$result$8.apply(Extraction.scala:584)
at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$result$8.apply(Extraction.scala:580)
at org.json4s.Extraction$.org$json4s$Extraction$$customOrElse(Extraction.scala:594)
at org.json4s.Extraction$ClassInstanceBuilder.result(Extraction.scala:580)
at org.json4s.Extraction$.extract(Extraction.scala:389)
at org.json4s.Extraction$.extract(Extraction.scala:39)
at scala.collection.AbstractMap.applyOrElse(Map.scala:59)
```

**Comment by hengkysucanda** [comment]
I found a similar bug https://github.com/NextGenTel/akka-tools/issues/15 which was fixed https://github.com/NextGenTel/akka-tools/commit/abcc7bfe39f05fb5bc597b0a289330ccf171c749 here by supporting SerializerWithStringManifest.

I'm still not very sure if it's the same case

**Comment by hengkysucanda** [comment]
So i have an Akka developer commenting on the thread https://groups.google.com/forum/#!topic/akka-user/68fQEYDNwMk it seems that the bug is with SerializerWithStringManifest implementation.

**Comment by pawelkaczor** [comment]
Issue in EventStore.Akka.Persistence created: EventStore/EventStore.Akka.Persistence#28

**Comment by hengkysucanda** [comment]
Additional information that led to the SaveSnapshotFailure:

```
Cannot deliver ReadStreamEventsCompleted(List(ResolvedEvent(EventRecord(Stream(Product-36a6e509-0c05-3567-a9a2-8b6487a79c0a),EventNumber(18),EventData(co.styletheory.context.inventory.domain.contracts.inventory.ProductBookedForSwapV2,d82f1759-f4d2-4abb-9b91-0b86656a6bea,Content(
...
Very, very long list of EventData
...
at akka.contrib.pattern.ReceivePipeline$$anonfun$combinedDecorator$1$$anonfun$2$$anonfun$apply$3.apply(ReceivePipeline.scala:77)
```

**Comment by hengkysucanda** [comment]
I am looking into the ReadStreamEventsCompleted message and honestly, the payload size is very huge, it contains all of my events data:

**Deleted because it has user email data**

Edit: I can actually control the size of this by managing the number of events being read by the EventStore.JVM library.

**Comment by hengkysucanda** [comment]
Im checking at the $et-akka.persistence.eventstore.snapshot.EventStoreSnapshotStore$SnapshotEvent$Snapshot streams, and one of the snapshot looks like this:

http://freetexthost.in/127065

It seems big (around 400Kb), i suspect it may be one of the cause why  `SaveSnapshotFailure(SnapshotMetadata(Receptor-products--739737088,3074,0),akka.pattern.CircuitBreakerOpenException: Circuit Breaker is open; calls are failing fast) is happening` because Snapshot is being written slowly.

**Comment by hengkysucanda** [comment]
Apparently, all i need to configure is: 
```
eventstore.persistence.snapshot-store.circuit-breaker {
   max-failures = 10 // increase this
   call-timeout = 10s // increase this
   reset-timeout = 30s // increase this
}
```

**Comment by pawelkaczor** [comment]
Good that you managed to solve that. 
The follow up issue: #32
