### ISSUE TITLE
Snapshot fails to be read when starting the application

### ISSUE THREAD

**Issue by hengkysucanda** [pawelkaczor/akka-ddd#32]
**Because i thought this should be a separate issue:**

Logs that i picked up:

```
at akka.persistence.eventstore.Helpers$RichConnection$.akka$persistence$eventstore$Helpers$RichConnection$$loop$1(Helpers.scala:52)
at akka.persistence.eventstore.Helpers$RichConnection$$anonfun$akka$persistence$eventstore$Helpers$RichConnection$$foldLeft$1$1.apply(Helpers.scala:57)
at akka.persistence.eventstore.Helpers$RichConnection$$anonfun$akka$persistence$eventstore$Helpers$RichConnection$$foldLeft$1$1.apply(Helpers.scala:56)
at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Unimplemented deserialization of message with manifest [akka.cluster.sharding.ShardCoordinator$Internal$State] in [akka.cluster.sharding.protobuf.ClusterShardingMessageSerializer]
at akka.cluster.sharding.protobuf.ClusterShardingMessageSerializer.fromBinary(ClusterShardingMessageSerializer.scala:162)
at akka.serialization.SerializerWithStringManifest.fromBinary(Serializer.scala:131)
at akka.serialization.Serialization$$anonfun$deserialize$3.apply(Serialization.scala:193)
at scala.util.Try$.apply(Try.scala:192)
at akka.serialization.Serialization.deserialize(Serialization.scala:193)
at pl.newicom.eventstore.json.SnapshotJsonSerializer$$anonfun$deserialize$1.applyOrElse(JsonSerializerExtension.scala:118)
at pl.newicom.eventstore.json.SnapshotJsonSerializer$$anonfun$deserialize$1.applyOrElse(JsonSerializerExtension.scala:112)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at pl.newicom.eventstore.json.ScheduledEventSerializer$$anonfun$deserialize$2.applyOrElse(JsonSerializerExtension.scala:84)
at pl.newicom.eventstore.json.ScheduledEventSerializer$$anonfun$deserialize$2.applyOrElse(JsonSerializerExtension.scala:84)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:393)
at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:393)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:393)
at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:393)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
... 31 more
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
at scala.collection.AbstractMap.applyOrElse(Map.scala:59)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.Extraction$.org$json4s$Extraction$$customOrElse(Extraction.scala:593)
at org.json4s.Extraction$ClassInstanceBuilder.result(Extraction.scala:580)
at org.json4s.Extraction$.extract(Extraction.scala:389)
at org.json4s.Extraction$ClassInstanceBuilder.org$json4s$Extraction$ClassInstanceBuilder$$mkWithTypeHint(Extraction.scala:575)
at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$result$8.apply(Extraction.scala:584)
at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$result$8.apply(Extraction.scala:580)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.Extraction$ClassInstanceBuilder.result(Extraction.scala:580)
at org.json4s.Extraction$.extract(Extraction.scala:389)
at org.json4s.Extraction$.extract(Extraction.scala:39)
at org.json4s.Extraction$.org$json4s$Extraction$$customOrElse(Extraction.scala:594)
org.json4s.package$MappingException: unknown error
at org.json4s.Extraction$.extract(Extraction.scala:43)
at org.json4s.ExtractableJsonAstNode.extract(ExtractableJsonAstNode.scala:21)
at org.json4s.native.Serialization$.read(Serialization.scala:71)
at org.json4s.Serialization$class.read(Serialization.scala:30)
at org.json4s.native.Serialization$.read(Serialization.scala:32)
at pl.newicom.eventstore.json.JsonSerializerExtensionImpl.fromBinary(JsonSerializerExtension.scala:44)
at pl.newicom.eventstore.EventstoreSerializationSupport$class.deserialize(EventstoreSerializationSupport.scala:98)
at pl.newicom.eventstore.EventstoreSerializationSupport$class.fromEvent(EventstoreSerializationSupport.scala:61)
at pl.newicom.eventstore.plugin.EventStoreSerializer.fromEvent(EventStoreSerializer.scala:10)
at pl.newicom.eventstore.plugin.EventStoreSerializer.fromEvent(EventStoreSerializer.scala:27)
at akka.persistence.eventstore.EventStoreSerialization.deserialize(EventStoreSerialization.scala:13)
at akka.persistence.eventstore.snapshot.EventStoreSnapshotStore$$anonfun$loadAsync$1$$anonfun$apply$1.applyOrElse(EventStoreSnapshotStore.scala:35)
at akka.persistence.eventstore.snapshot.EventStoreSnapshotStore$$anonfun$loadAsync$1$$anonfun$apply$1.applyOrElse(EventStoreSnapshotStore.scala:35)
at akka.persistence.eventstore.snapshot.EventStoreSnapshotStore$$anonfun$loadAsync$1.akka$persistence$eventstore$snapshot$EventStoreSnapshotStore$$anonfun$$fold$1(EventStoreSnapshotStore.scala:24)
at scala.PartialFunction$Lifted.apply(PartialFunction.scala:223)
at scala.PartialFunction$Lifted.apply(PartialFunction.scala:219)
at akka.persistence.eventstore.Helpers$RichConnection$.akka$persistence$eventstore$Helpers$RichConnection$$loop$1(Helpers.scala:52)
at akka.persistence.eventstore.Helpers$RichConnection$$anonfun$akka$persistence$eventstore$Helpers$RichConnection$$foldLeft$1$1.apply(Helpers.scala:57)
at akka.persistence.eventstore.Helpers$RichConnection$$anonfun$akka$persistence$eventstore$Helpers$RichConnection$$foldLeft$1$1.apply(Helpers.scala:56)
at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
at akka.serialization.Serialization$$anonfun$deserialize$3.apply(Serialization.scala:193)
at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Unimplemented deserialization of message with manifest [akka.cluster.sharding.ShardCoordinator$Internal$State] in [akka.cluster.sharding.protobuf.ClusterShardingMessageSerializer]
at akka.cluster.sharding.protobuf.ClusterShardingMessageSerializer.fromBinary(ClusterShardingMessageSerializer.scala:162)
at akka.serialization.SerializerWithStringManifest.fromBinary(Serializer.scala:131)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
at scala.util.Try$.apply(Try.scala:192)
at akka.serialization.Serialization.deserialize(Serialization.scala:193)
at pl.newicom.eventstore.json.SnapshotJsonSerializer$$anonfun$deserialize$1.applyOrElse(JsonSerializerExtension.scala:118)
at pl.newicom.eventstore.json.SnapshotJsonSerializer$$anonfun$deserialize$1.applyOrElse(JsonSerializerExtension.scala:112)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at pl.newicom.eventstore.json.ScheduledEventSerializer$$anonfun$deserialize$2.applyOrElse(JsonSerializerExtension.scala:84)
at pl.newicom.eventstore.json.ScheduledEventSerializer$$anonfun$deserialize$2.applyOrElse(JsonSerializerExtension.scala:84)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:393)
at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:393)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:393)
at org.json4s.CustomSerializer$$anonfun$deserialize$1.applyOrElse(Formats.scala:393)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
... 31 more
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at org.json4s.ext.EnumSerializer$$anonfun$deserialize$1.applyOrElse(EnumSerializer.scala:34)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
at org.json4s.Extraction$.org$json4s$Extraction$$customOrElse(Extraction.scala:593)
at org.json4s.Extraction$ClassInstanceBuilder.result(Extraction.scala:580)
at org.json4s.Extraction$.extract(Extraction.scala:389)
at org.json4s.Extraction$ClassInstanceBuilder.org$json4s$Extraction$ClassInstanceBuilder$$mkWithTypeHint(Extraction.scala:575)
at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$result$8.apply(Extraction.scala:584)
at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$result$8.apply(Extraction.scala:580)
at org.json4s.Extraction$.org$json4s$Extraction$$customOrElse(Extraction.scala:594)
at org.json4s.Extraction$ClassInstanceBuilder.result(Extraction.scala:580)
at org.json4s.Extraction$.extract(Extraction.scala:389)
at org.json4s.Extraction$.extract(Extraction.scala:39)
at scala.collection.AbstractMap.applyOrElse(Map.scala:59)
```

**Comment by hengkysucanda** [comment]
Not sure if related, but im now getting:

```
Persistence failure when replaying events for persistenceId [usersSaga-email%40gmail.com]. Last known sequence number [0]
```
in looping.

**Comment by pawelkaczor** [comment]
Thanks for reporting. 

For reference, the issue was diagnosed here: EventStore/EventStore.Akka.Persistence#28.

**Comment by hengkysucanda** [comment]
Hi @pawelkaczor, do you have any ETA on when the bugfix is going to be released?

**Comment by pawelkaczor** [comment]
I will try to fix it tomorrow.
